name: publish to gh pages
on:
  workflow_dispatch:
  push:
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout routr repo
      uses: actions/checkout@v3
      with:
        repository: fonoster/routr
        path: routr
    - name: Create and populate out directory
      run: |
        mkdir -p out
        cp -R routr/.charts/ out/
    - name: Checkout current repo
      uses: actions/checkout@v3
    - name: Installing Node
      uses: actions/setup-node@v3
      with:
        node-version: "18.x"
    - name: Build
      run: |
        npm install
        npm run build
        cp -R build/* out/
        mkdir -p out/site-assets
        cp -R site/assets/* out/site-assets/
        cp site/index.html out/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_PAT }}
        external_repository: fonoster/routr
        publish_branch: gh-pages
        publish_dir: ./out
        cname: routr.io
