name: publish to gh pages
on:
  workflow_dispatch:
  push:
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Installing Node
      uses: actions/setup-node@v3
      with:
        node-version: "18.x"
    - name: Build
      run: |
        npm run build
        mv build out
        mv site/assets out/site-assets
        mv site/index.html out/index.html
        echo "routr.io" > out/CNAME
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        external_repository: fonoster/routr
        publish_branch: gh-pages
        publish_dir: ./out
